### ISSUE TITLE
Porting the codebase to github and refactoring of parts of the codebase 

### ISSUE THREAD

**Issue by lepatrick714** [lepatrick714/Full_Sensor_Senior_Design#3]
Low priority. Will streamline and make code a lot nicer to view. Will increase any future development.

**Comment by lepatrick714** [comment]
Link to code: 
https://docs.google.com/a/ucr.edu/document/d/1ZN6Co1ysxu5bGRNr_p9JddJ1ASsA5so4CG6Zw6zR5AU/edit?usp=sharing

Checklist
- [x] Porting code to this Github repo
- [x] Refactoring if statements to switch statements
- [x] Move all constant variables to a separate file and add reference to said file to the program
- [ ] Integrate the program to an object oriented style. 
- [ ] Provide a driver ( main.cpp ) file that will run the codebase.

**Comment by RBoshae** [comment]
Is the goal to copy the code line by line from the Google Doc or work with what is in the compute.cpp file?

**Comment by RBoshae** [comment]
I noticed at the end of compute.cpp references are made to undefined code. Is this meant to be linked to another file?

**Comment by lepatrick714** [comment]
Richie will be completing the program. He'll comment his c9.io workspace once it's completed. He'll update you accordingly.

As for copying line by line, no. You don't have to do that. Might be better to clean up the code and add some comments doe. 

Could you place this new feature in a separate directory inside of src? We can edit the makefile in the future.

**Comment by lepatrick714** [comment]
@RBoshae Richee just updated the compute.cpp file. I've committed it to master. Could you prettify it? :)

**Comment by RBoshae** [comment]
@lepatrick714 Pull request in.

**Comment by lepatrick714** [comment]
I will be closing this issue since the other requirements would be better suited as a new ticket.
